//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionSite.Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuctionSite.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Active benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Active Auctions benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ActiveAuctions {
            get {
                return ResourceManager.GetString("ActiveAuctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while processing your request. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AnErrorOccurred {
            get {
                return ResourceManager.GetString("AnErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete this? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AreYouSureToDelete {
            get {
                return ResourceManager.GetString("AreYouSureToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auction created successfully! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AuctionCreatedSuccessfully {
            get {
                return ResourceManager.GetString("AuctionCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auction deleted successfully! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AuctionDeletedSuccessfully {
            get {
                return ResourceManager.GetString("AuctionDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auction Details benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AuctionDetails {
            get {
                return ResourceManager.GetString("AuctionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This auction has expired. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AuctionExpired {
            get {
                return ResourceManager.GetString("AuctionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This auction has expired and cannot receive new bids. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AuctionExpiredCannotBid {
            get {
                return ResourceManager.GetString("AuctionExpiredCannotBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auction Ended benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AuctionExpiredMessage {
            get {
                return ResourceManager.GetString("AuctionExpiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auction Item benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AuctionItem {
            get {
                return ResourceManager.GetString("AuctionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The {0} must not exceed {1} characters. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AuctionItem_DescriptionLength {
            get {
                return ResourceManager.GetString("AuctionItem_DescriptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The {0} must not exceed {1} characters. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AuctionItem_NameLength {
            get {
                return ResourceManager.GetString("AuctionItem_NameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auction Items benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AuctionItems {
            get {
                return ResourceManager.GetString("AuctionItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auction not found. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AuctionNotFound {
            get {
                return ResourceManager.GetString("AuctionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This auction has not started yet. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AuctionNotStartedYet {
            get {
                return ResourceManager.GetString("AuctionNotStartedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auction Site Support benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AuctionSiteSupport {
            get {
                return ResourceManager.GetString("AuctionSiteSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auction Started! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AuctionStarted {
            get {
                return ResourceManager.GetString("AuctionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auction updated successfully! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AuctionUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("AuctionUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back to Details benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BackToDetails {
            get {
                return ResourceManager.GetString("BackToDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back to List benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back to Manage Account benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BackToManageAccount {
            get {
                return ResourceManager.GetString("BackToManageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The bid amount must be greater than 0. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BidAmountRange {
            get {
                return ResourceManager.GetString("BidAmountRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The bid amount is required. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BidAmountRequired {
            get {
                return ResourceManager.GetString("BidAmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your bid amount must be at least {0}. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BidAmountTooLow {
            get {
                return ResourceManager.GetString("BidAmountTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bid History benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BidHistory {
            get {
                return ResourceManager.GetString("BidHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your bid must be higher than the current price ({0}). benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BidMustBeHigherThanCurrentPrice {
            get {
                return ResourceManager.GetString("BidMustBeHigherThanCurrentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your bid must be at least {0} higher than the current price. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BidMustMeetMinimumIncrement {
            get {
                return ResourceManager.GetString("BidMustMeetMinimumIncrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your bid has been placed successfully! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BidPlacedSuccessfully {
            get {
                return ResourceManager.GetString("BidPlacedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Explore Auctions benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BrowseAuctionsButton {
            get {
                return ResourceManager.GetString("BrowseAuctionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You cannot bid on your own auction. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CannotBidOnOwnAuction {
            get {
                return ResourceManager.GetString("CannotBidOnOwnAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This auction cannot be deleted because it is active, expired, or has bids. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CannotDeleteActiveOrBiddedAuction {
            get {
                return ResourceManager.GetString("CannotDeleteActiveOrBiddedAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This auction cannot be edited because it is active, expired, or has bids. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CannotEditActiveOrBiddedAuction {
            get {
                return ResourceManager.GetString("CannotEditActiveOrBiddedAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This auction cannot be edited because it is active or has expired. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CannotEditActiveOrExpiredAuction {
            get {
                return ResourceManager.GetString("CannotEditActiveOrExpiredAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Email benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ChangeEmail {
            get {
                return ResourceManager.GetString("ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Password benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Username benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ChangeUsername {
            get {
                return ResourceManager.GetString("ChangeUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check Current Email benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CheckCurrentEmail {
            get {
                return ResourceManager.GetString("CheckCurrentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check New Email benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CheckNewEmail {
            get {
                return ResourceManager.GetString("CheckNewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ColonSeparator {
            get {
                return ResourceManager.GetString("ColonSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirmed benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm New Password benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm Password benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The uploaded image file is corrupted or invalid. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CorruptedImage {
            get {
                return ResourceManager.GetString("CorruptedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create New benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create New Auction benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CreateNewAuction {
            get {
                return ResourceManager.GetString("CreateNewAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Bid benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CurrentBid {
            get {
                return ResourceManager.GetString("CurrentBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Bidder benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CurrentBidder {
            get {
                return ResourceManager.GetString("CurrentBidder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Price benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CurrentPrice {
            get {
                return ResourceManager.GetString("CurrentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   d  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DaysShort {
            get {
                return ResourceManager.GetString("DaysShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Auction benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeleteAuction {
            get {
                return ResourceManager.GetString("DeleteAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Details benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Development Mode benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DevelopmentMode {
            get {
                return ResourceManager.GetString("DevelopmentMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;strong&gt;Development&lt;/strong&gt; environment will display more detailed information about the error that occurred. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DevelopmentModeExplanation1 {
            get {
                return ResourceManager.GetString("DevelopmentModeExplanation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   For local debugging, enable the &lt;strong&gt;Development&lt;/strong&gt; environment by setting the &lt;strong&gt;ASPNETCORE_ENVIRONMENT&lt;/strong&gt; environment variable to &lt;strong&gt;Development&lt;/strong&gt; and restarting the app. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DevelopmentModeExplanation2 {
            get {
                return ResourceManager.GetString("DevelopmentModeExplanation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The &lt;strong&gt;Development&lt;/strong&gt; environment shouldn&apos;t be enabled for deployed applications. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DevelopmentModeWarning1 {
            get {
                return ResourceManager.GetString("DevelopmentModeWarning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It can result in displaying sensitive information from exceptions to end users. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DevelopmentModeWarning2 {
            get {
                return ResourceManager.GetString("DevelopmentModeWarning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Auction benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EditAuction {
            get {
                return ResourceManager.GetString("EditAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter a valid email address. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email address is required. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email &apos;{0}&apos; successfully sent to &apos;{1}&apos;. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EmailSentSuccessfully {
            get {
                return ResourceManager.GetString("EmailSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End Time benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End time must be a valid date. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EndTimeCannotBeMinValue {
            get {
                return ResourceManager.GetString("EndTimeCannotBeMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End time must be after the start time. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EndTimeMustBeAfterStartTime {
            get {
                return ResourceManager.GetString("EndTimeMustBeAfterStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End Time is required. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EndTimeRequired {
            get {
                return ResourceManager.GetString("EndTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End Time benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EndTimeText {
            get {
                return ResourceManager.GetString("EndTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Forgot your password? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ForgotPasswordLink {
            get {
                return ResourceManager.GetString("ForgotPasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hello benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://images.pexels.com/photos/5668473/pexels-photo-5668473.jpeg benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HeroBackgroundImageUrl {
            get {
                return ResourceManager.GetString("HeroBackgroundImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   h  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HoursShort {
            get {
                return ResourceManager.GetString("HoursShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Participating in auctions or selling your own products on our site is very easy! Here is our step-by-step guide: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HowItWorksIntro {
            get {
                return ResourceManager.GetString("HowItWorksIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error deleting image: {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ImageDeletionErrorMessage {
            get {
                return ResourceManager.GetString("ImageDeletionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You have insufficient virtual balance to place this bid. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string InsufficientBalance {
            get {
                return ResourceManager.GetString("InsufficientBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid auction ID. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string InvalidAuctionId {
            get {
                return ResourceManager.GetString("InvalidAuctionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only JPG, JPEG, PNG, GIF, or BMP image extensions can be uploaded. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string InvalidImageExtension {
            get {
                return ResourceManager.GetString("InvalidImageExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The uploaded file is not a valid image. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string InvalidImageMimeType {
            get {
                return ResourceManager.GetString("InvalidImageMimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Latest Bids benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LatestBids {
            get {
                return ResourceManager.GetString("LatestBids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login is required. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LoginRequired {
            get {
                return ResourceManager.GetString("LoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You must be logged in to place a bid. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LoginRequiredToBid {
            get {
                return ResourceManager.GetString("LoginRequiredToBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You must be logged in to create an auction. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LoginRequiredToCreateAuction {
            get {
                return ResourceManager.GetString("LoginRequiredToCreateAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You have successfully logged in. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login to bid benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LoginToBid {
            get {
                return ResourceManager.GetString("LoginToBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please login to place a bid. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LoginToPlaceBid {
            get {
                return ResourceManager.GetString("LoginToPlaceBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logout benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Successfully logged out. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LogoutSuccess {
            get {
                return ResourceManager.GetString("LogoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manage Account benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ManageAccount {
            get {
                return ResourceManager.GetString("ManageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimum Bid Increment benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MinimumBidIncrement {
            get {
                return ResourceManager.GetString("MinimumBidIncrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimum Bid Increment must be greater than 0. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MinimumBidIncrementRange {
            get {
                return ResourceManager.GetString("MinimumBidIncrementRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimum Bid Increment is required. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MinimumBidIncrementRequired {
            get {
                return ResourceManager.GetString("MinimumBidIncrementRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimum Next Bid benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MinimumNextBid {
            get {
                return ResourceManager.GetString("MinimumNextBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   m  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MinutesShort {
            get {
                return ResourceManager.GetString("MinutesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My Auctions benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MyAuctions {
            get {
                return ResourceManager.GetString("MyAuctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Email benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NewEmail {
            get {
                return ResourceManager.GetString("NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New email address is required. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NewEmailRequired {
            get {
                return ResourceManager.GetString("NewEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Password benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The new password and confirmation password do not match. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NewPasswordMismatch {
            get {
                return ResourceManager.GetString("NewPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New password is required. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NewPasswordRequired {
            get {
                return ResourceManager.GetString("NewPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Username benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NewUsername {
            get {
                return ResourceManager.GetString("NewUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no active auctions at the moment. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NoActiveAuctions {
            get {
                return ResourceManager.GetString("NoActiveAuctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No bids have been placed yet. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NoBidsYet {
            get {
                return ResourceManager.GetString("NoBidsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no expired auctions at the moment. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NoExpiredAuctions {
            get {
                return ResourceManager.GetString("NoExpiredAuctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Image Available benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NoImageAvailable {
            get {
                return ResourceManager.GetString("NoImageAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Confirmed benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NotConfirmed {
            get {
                return ResourceManager.GetString("NotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no upcoming auctions at the moment. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NoUpcomingAuctions {
            get {
                return ResourceManager.GetString("NoUpcomingAuctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No winner for this auction. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NoWinner {
            get {
                return ResourceManager.GetString("NoWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Old Password benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current password is required. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string OldPasswordRequired {
            get {
                return ResourceManager.GetString("OldPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The password and confirmation password do not match. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password is required. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A link to reset your password has been sent to your email address. Please check your email. If you do not receive the email, please check your spam/junk folder. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PasswordResetConfirmationMessage {
            get {
                return ResourceManager.GetString("PasswordResetConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password Reset Confirmation benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PasswordResetConfirmationTitle {
            get {
                return ResourceManager.GetString("PasswordResetConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Phone Number benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter a valid phone number. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PhoneNumberInvalid {
            get {
                return ResourceManager.GetString("PhoneNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your phone number has been updated successfully. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PhoneNumberUpdateSuccess {
            get {
                return ResourceManager.GetString("PhoneNumberUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Place Bid benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PlaceBid {
            get {
                return ResourceManager.GetString("PlaceBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Privacy benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Product Name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Product Name is required. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProductNameRequired {
            get {
                return ResourceManager.GetString("ProductNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile Information benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProfileInformation {
            get {
                return ResourceManager.GetString("ProfileInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register as a new user benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RegisterNewUser {
            get {
                return ResourceManager.GetString("RegisterNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register Now benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RegisterNowButton {
            get {
                return ResourceManager.GetString("RegisterNowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remember me benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Request ID benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RequestID {
            get {
                return ResourceManager.GetString("RequestID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resend Confirmation Email benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ResendConfirmationEmail {
            get {
                return ResourceManager.GetString("ResendConfirmationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset Password benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ResetPasswordButton {
            get {
                return ResourceManager.GetString("ResetPasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset your password. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ResetPasswordInstructions {
            get {
                return ResourceManager.GetString("ResetPasswordInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset Password benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ResetPasswordTitle {
            get {
                return ResourceManager.GetString("ResetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   s  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SecondsShort {
            get {
                return ResourceManager.GetString("SecondsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seller benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Seller {
            get {
                return ResourceManager.GetString("Seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Phone Number benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SetPhoneNumber {
            get {
                return ResourceManager.GetString("SetPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SMTP error occurred while sending email: {0} - {1} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SmtpErrorSendingEmail {
            get {
                return ResourceManager.GetString("SmtpErrorSendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SMTP settings are missing: Host, Username, or Password is empty. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SmtpSettingsMissing {
            get {
                return ResourceManager.GetString("SmtpSettingsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///     benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Starting Price benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string StartingPrice {
            get {
                return ResourceManager.GetString("StartingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Starting Price must be greater than 0. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string StartingPriceRange {
            get {
                return ResourceManager.GetString("StartingPriceRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Starting Price is required. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string StartingPriceRequired {
            get {
                return ResourceManager.GetString("StartingPriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Time benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start time cannot be in the past. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string StartTimeCannotBeInPast {
            get {
                return ResourceManager.GetString("StartTimeCannotBeInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start time must be a valid date. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string StartTimeCannotBeMinValue {
            get {
                return ResourceManager.GetString("StartTimeCannotBeMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Time is required. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string StartTimeRequired {
            get {
                return ResourceManager.GetString("StartTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The {0} must be at least {2} and at most {1} characters long. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string StringLengthValidation {
            get {
                return ResourceManager.GetString("StringLengthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You have successfully registered and logged in. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SuccessfullyRegisteredAndLoggedIn {
            get {
                return ResourceManager.GetString("SuccessfullyRegisteredAndLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time Expired! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TimeExpired {
            get {
                return ResourceManager.GetString("TimeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time Expired benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TimeExpiredMessage {
            get {
                return ResourceManager.GetString("TimeExpiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time remaining benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TimeRemaining {
            get {
                return ResourceManager.GetString("TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time until start benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TimeUntilStart {
            get {
                return ResourceManager.GetString("TimeUntilStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Describe your product&apos;s features (size, material, condition), any flaws, and why it&apos;s special. Convince buyers! (Minimum 50 words recommended) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Tip_Description {
            get {
                return ResourceManager.GetString("Tip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose when your auction will end. It must be after the start time. Allow sufficient time to receive more bids. (e.g., &apos;07/22/2025 10:00 PM&apos;) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Tip_EndTime {
            get {
                return ResourceManager.GetString("Tip_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upload high-quality, clear photos of your product from different angles. Good visuals attract buyers and build trust. (Max 5MB, JPG/PNG) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Tip_Image {
            get {
                return ResourceManager.GetString("Tip_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Determine the minimum amount each new bid must increase the current bid by. Smaller increments can encourage more competition. (e.g., $5.00) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Tip_MinimumBidIncrement {
            get {
                return ResourceManager.GetString("Tip_MinimumBidIncrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose a short, memorable name that best describes your product. (e.g., &apos;Antique Silver Pocket Watch&apos;, &apos;Handmade Ceramic Vase&apos;) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Tip_ProductName {
            get {
                return ResourceManager.GetString("Tip_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set the minimum price your auction will start at. A realistic price can attract more bids. (e.g., $100.00) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Tip_StartingPrice {
            get {
                return ResourceManager.GetString("Tip_StartingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select when your auction will begin. It must be a future date and time. (e.g., &apos;07/15/2025 10:00 AM&apos;) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Tip_StartTime {
            get {
                return ResourceManager.GetString("Tip_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are not authorized to delete this auction. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UnauthorizedDeleteAttempt {
            get {
                return ResourceManager.GetString("UnauthorizedDeleteAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are not authorized to edit this auction. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UnauthorizedEdit {
            get {
                return ResourceManager.GetString("UnauthorizedEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are not authorized to edit this auction. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UnauthorizedEditAttempt {
            get {
                return ResourceManager.GetString("UnauthorizedEditAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error occurred while sending email: {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UnexpectedErrorSendingEmail {
            get {
                return ResourceManager.GetString("UnexpectedErrorSendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error occurred during image upload. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UnexpectedErrorUploadingImage {
            get {
                return ResourceManager.GetString("UnexpectedErrorUploadingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upcoming Auctions benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UpcomingAuctions {
            get {
                return ResourceManager.GetString("UpcomingAuctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upload New Image (optional) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UploadNewImage {
            get {
                return ResourceManager.GetString("UploadNewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use a local account to log in. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UseALocalAccountToLogin {
            get {
                return ResourceManager.GetString("UseALocalAccountToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Username benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Username is required. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verification Code benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verification code is required. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string VerificationCodeRequired {
            get {
                return ResourceManager.GetString("VerificationCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verify Code benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string VerifyCode {
            get {
                return ResourceManager.GetString("VerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verify Old Email benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string VerifyOldEmail {
            get {
                return ResourceManager.GetString("VerifyOldEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View Details benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Virtual Balance benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string VirtualBalance {
            get {
                return ResourceManager.GetString("VirtualBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Welcome to our Auction Site! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Winner benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Winner {
            get {
                return ResourceManager.GetString("Winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Winning Auctions benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string WinningAuctions {
            get {
                return ResourceManager.GetString("WinningAuctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your Auctions benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YourAuctions {
            get {
                return ResourceManager.GetString("YourAuctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your Bid benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YourBid {
            get {
                return ResourceManager.GetString("YourBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your Bids benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YourBids {
            get {
                return ResourceManager.GetString("YourBids", resourceCulture);
            }
        }
    }
}
